# Site settings
title: Rohin's blog 
description: >- # this means to ignore newlines until "baseurl:"
 Machine Learning, Computer Vision, Life Etc 
baseurl: "" 
url: "http://rohinarora.github.io" 
twitter_username: rohin363
github_username: rohinarora 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

